on: push

jobs:
  Scripts:
    name: "Unit Test Scripts"
    runs-on: ubuntu-latest

    steps:
      - name: Install Lua
        run: |
          sudo apt-get update
          sudo apt-get install -y lua5.4

      - uses: actions/checkout@v4

      - name: Run script unit tests
        run: |
          find test -name test.sh -executable -print -execdir ./{} \;